config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'restaurants', to: 'restaurants#index'
  get 'restaurants/new', to: 'restaurants#new'
  get 'restaurants/:id', to: 'restaurants#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :category, inclusion: { in: %w(chinese italian japanese french belgian),
    message: "%{value} is not a valid category" }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, :rating, presence: true
  validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.create(restaurant_params)
  end
  private
  def restaurant_params
    params.require.permit(:name, :address, :phone_number, :category)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<center><h1>Restaurants</h1></center>

<ul>
  <% @restaurants.each do |restaurant| %>
  <li><%= restaurant.name %></li>
  <% end %>
</ul>

<%= link_to 'Enter new Restaurant', restaurants_new_path %>

app/views/restaurants/new.html.erb
<center><h1>Add a new Restaurant</h1></center>

<%= form_for :restaurant do |form| %>
  Restaurant name: <%= form.text_field :name %><br />
  Address: <%= form.text_field :address %><br />
  Phone number : <%= form.text_area :phone_number %><br />
  Category    : <%= form.text_field :category %><br />
  <%= form.submit %>
<% end %>

app/views/restaurants/show.html.erb
<center><h1><%= @restaurant.name %></h1></center>

<center>
  <h3>adress</h3>
  <%= @restaurant.address %>
  <%= @restaurant.phone_number %>
</center>

<center>
  <h3>speciality</h3>
  <%= @restaurant.category %>
</center>